version: '3.12'

services:
  flight-service:
    build:
      context: ./backend/flight-service
    ports:
      - "8001:8001"
    # deploy:
    #   replicas: 3

  inventory-service:
    build:
      context: ./backend/inventory-service
    ports:
      - "8002:8002"
    # deploy:
    #   replicas: 2

  payment-service:
    build:
      context: ./backend/payment-service
    ports:
      - "8003:8003"
    # deploy:
    #   replicas: 3

  customer-service:
    build:
      context: ./backend/customer-service
    ports:
      - "8004:8004"
    # deploy:
    # replicas: 1

  predictive-maintenance-service:
    build:
      context: ./backend/maintenance-service
    ports:
      - "8007:8007"
    # deploy:
    #   replicas: 3

  notification-service:
    build:
      context: ./backend/notification-service
    ports:
      - "8006:8006"
    # deploy:
    #   replicas: 2

  # loadbalancer:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - customer-service
  #     - flight-service
  #     - inventory-service
  #     - maintenance-service
  #     - notification-service
  #     - payment-service